# .github/workflows/deploy-services.yml

name: Test Workflow Trigger

on:
  push:
    branches: [ main ]

jobs:
  test-trigger-job:
    runs-on: ubuntu-latest
    steps:
      - name: A simple step to confirm the workflow is running
        run: echo "The deploy-services.yml workflow was triggered successfully!"